#include "keys.h"

#include <stddef.h>
#include <string.h>

#define XK_LATIN1
#define XK_MISCELLANY
#include <X11/keysymdef.h>

struct key_list_entry keys[] = {
	{ "0", XK_0 },
	{ "1", XK_1 },
	{ "2", XK_2 },
	{ "3", XK_3 },
	{ "4", XK_4 },
	{ "5", XK_5 },
	{ "6", XK_6 },
	{ "7", XK_7 },
	{ "8", XK_8 },
	{ "9", XK_9 },
	{ "a", XK_a },
	{ "b", XK_b },
	{ "c", XK_c },
	{ "d", XK_d },
	{ "e", XK_e },
	{ "f", XK_f },
	{ "g", XK_g },
	{ "h", XK_h },
	{ "i", XK_i },
	{ "j", XK_j },
	{ "k", XK_k },
	{ "l", XK_l },
	{ "m", XK_m },
	{ "n", XK_n },
	{ "o", XK_o },
	{ "p", XK_p },
	{ "q", XK_q },
	{ "r", XK_r },
	{ "s", XK_s },
	{ "t", XK_t },
	{ "u", XK_u },
	{ "v", XK_v },
	{ "w", XK_w },
	{ "x", XK_x },
	{ "y", XK_y },
	{ "z", XK_z },
	{ "kp_ins", 0 },
	{ "kp_end", 0 },
	{ "kp_downarrow", 0 },
	{ "kp_pgdn", 0 },
	{ "kp_leftarrow", 0 },
	{ "kp_5", 0 },
	{ "kp_rightarrow", 0 },
	{ "kp_home", 0 },
	{ "kp_uparrow", 0 },
	{ "kp_pgup", 0 },
	{ "kp_slash", 0 },
	{ "kp_multiply", 0 },
	{ "kp_minus", 0 },
	{ "kp_plus", 0 },
	{ "kp_enter", 0 },
	{ "kp_del", 0 },
	{ "[", 0 },
	{ "]", 0 },
	{ "semicolon", 0 },
	{ "'", 0 },
	{ "`", 0 },
	{ ",", 0 },
	{ ".", 0 },
	{ "/", 0 },
	{ "\\", 0 },
	{ "-", 0 },
	{ "=", 0 },
	{ "enter", 0 },
	{ "space", 0 },
	{ "backspace", 0 },
	{ "tab", 0 },
	{ "capslock", 0 },
	{ "numlock", 0 },
	{ "escape", 0 },
	{ "scrolllock", 0 },
	{ "ins", 0 },
	{ "del", 0 },
	{ "home", 0 },
	{ "end", 0 },
	{ "pgup", 0 },
	{ "pgdn", 0 },
	{ "pause", 0 },
	{ "shift", 0 },
	{ "rshift", 0 },
	{ "alt", 0 },
	{ "ralt", 0 },
	{ "ctrl", 0 },
	{ "rctrl", 0 },
	{ "lwin", 0 },
	{ "rwin", 0 },
	{ "app", 0 },
	{ "uparrow", 0 },
	{ "leftarrow", 0 },
	{ "downarrow", 0 },
	{ "rightarrow", 0 },
	{ "f1", XK_F1 },
	{ "f2", XK_F2 },
	{ "f3", XK_F3 },
	{ "f4", XK_F4 },
	{ "f5", XK_F5 },
	{ "f6", XK_F6 },
	{ "f7", XK_F7 },
	{ "f8", XK_F8 },
	{ "f9", XK_F9 },
	{ "f10", XK_F10 },
	{ "f11", XK_F11 },
	{ "f12", XK_F12 },

	{ "capslocktoggle", 0 },
	{ "numlocktoggle", 0 },
	{ "scrolllocktoggle", 0 },

	{ "mouse1", 0 },
	{ "mouse2", 0 },
	{ "mouse3", 0 },
	{ "mouse4", 0 },
	{ "mouse5", 0 },

	{ "mwheelup", 0 },
	{ "mwheeldown", 0 },

#if defined(__linux__)
	{ "a_button", 0 },
	{ "b_button", 0 },
	{ "x_button", 0 },
	{ "y_button", 0 },
	{ "l_shoulder", 0 },
	{ "r_shoulder", 0 },
	{ "back", 0 },
	{ "start", 0 },
	{ "stick1", 0 },
	{ "stick2", 0 },
#else
	{ "joy1", 0 },
	{ "joy2", 0 },
	{ "joy3", 0 },
	{ "joy4", 0 },
	{ "joy5", 0 },
	{ "joy6", 0 },
	{ "joy7", 0 },
	{ "joy8", 0 },
	{ "joy9", 0 },
	{ "joy10", 0 },
#endif
	{ NULL, 0 },
};

KeySym keys_name2keysym(const char *name) {
	for (struct key_list_entry *p = keys; p->name != NULL; p++) {
		if (strcmp(p->name, name) == 0) {
			return p->xkey;
		}
	}
	return 0;
}
