name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-groovy

    steps:
    - uses: actions/checkout@v2
    - name: deps
      run: sudo apt install build-essential clang libfuse3-dev liblua5.4-dev libx11-dev libxtst-dev
    - name: make
      run: make
      env:
        CFLAGS: -O2 -Werror
