name: wasteotime
on:
  push:
    branches: [ master, today ]
  pull_request:
    branches: [ master, today ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: deps
      run: sudo apt-get install build-essential clang libfuse3-dev libx11-dev libxtst-dev libbsd-dev
    - name: ci.sh
      run: sh .github/ci.sh
